services:
  ssh-server1:
    build: .
    hostname: ssh-server1
    container_name: ssh-server1
    volumes:
      - ssh-keys-server1:/etc/ssh
    ports:
      - "127.0.0.1:2222:22"

  ssh-server2:
    build: .
    hostname: ssh-server2
    container_name: ssh-server2
    volumes:
      - ssh-keys-server2:/etc/ssh
    ports:
      - "127.0.0.1:2223:22"

volumes:
  ssh-keys-server1:
  ssh-keys-server2:
