services:
  ssh-server1:
    build: .
    hostname: ssh-server1
    cap_add:
      - SYS_ADMIN
    container_name: ssh-server1
    volumes:
      - ssh-keys-server1:/etc/ssh
    ports:
      - "2222:22"  # Map port for SSH access

  ssh-server2:
    build: .
    hostname: ssh-server2
    cap_add:
      - SYS_ADMIN
    container_name: ssh-server2
    volumes:
      - ssh-keys-server2:/etc/ssh
    ports:
      - "2223:22"  # Map port for SSH access

volumes:
  ssh-keys-server1:
  ssh-keys-server2:
  